= Quarkus logging splunk

== Introduction

https://www.splunk.com/en_us/software/splunk-enterprise.html[Splunk] is a middleware
solution that receives, stores, indexes and finally allows to exploit the logs of an application.

This Quarkus extension provides the support of the official Splunk client library to index log events through the HTTP Event collection, provided by Splunk enterprise solution.

- The official client is an opensource library available https://github.com/splunk/splunk-library-javalogging[here].
- The documentation of HTTP Event collection can be found https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/UsetheHTTPEventCollector[here].

== Installation

If you want to use this extension, you need to add the `quarkus-logging-splunk` extension first.
In your `pom.xml` file, add:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkus-logging-splunk</artifactId>
</dependency>
----

== Configuration

=== Convention

This extension follows the `log handlers` configuration domain that is defined by Quarkus, every configuration property of this extension will belong to the following configuration root : `quarkus.log.handler.splunk`

=== Default behaviour

When used this extension is enabled by default, meaning the the client would expect a valid connection to a Splunk indexer and would print an error message for every log created by the application.

So in local environment, the log handler can be disabled with the following property :

[source,properties]
----
quarkus.log.handler.splunk.enabled=false
----

=== Extension Configuration Reference

Every configuration property of the extension is overridable at runtime.

include::config.adoc[leveloffset=+1, opts=optional]

== Usage

The extension can be used transparently with any log frontend used by Quarkus (Log4j, SLF4J, ... )

The default log format of the extension is the following:

[source,properties]
----
quarkus.log.handler.splunk.format="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
----

=== Connectivity failures

Batched events that cannot be sent to the Splunk indexer will be logged to stdout:

* Formatted using console handler settings if the console handler is enabled 
* Formatted using splunk handler settings otherwise

In any case, the root cause of the failure is always logged to stderr.

=== MDC support

In addition to the original client library this extension provides the support of the resolution of MDC scoped properties as defined in https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/logging_with_jboss_eap#log_formatters[JBoss supported formatters].
Then properties are sent as https://docs.splunk.com/Splexicon\:Indexedfield[indexed fields] in the Splunk log event.
