= Quarkus logging splunk

== Introduction

https://www.splunk.com/en_us/software/splunk-enterprise.html[Splunk] is a middleware
solution that receives, stores, indexes and finally allows to exploit the logs of an application.

This Quarkus extension provides the support of the official Splunk client library to index log events through the HTTP Event collection, provided by Splunk enterprise solution.

- The official client is an opensource library available https://github.com/splunk/splunk-library-javalogging[here].
- The documentation of HTTP Event collection can be found https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/UsetheHTTPEventCollector[here].

== Installation

If you want to use this extension, you need to add the `quarkus-logging-splunk` extension first.
In your `pom.xml` file, add:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.logging.splunk</groupId>
    <artifactId>quarkus-logging-splunk</artifactId>
</dependency>
----

== Features

The extension can be used transparently with any log frontend used by Quarkus (Log4j, SLF4J, ... ).

=== Structured vs raw log events

Unless `quarkus.log.handler.splunk.raw` is enabled, the extension uses structured logging.

The log message format is aligned with the one of Quarkus console handler:

[source,properties]
----
quarkus.log.handler.splunk.format="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
----

By default, only few structured metadata computed by the HEC client library are sent.
Extra metadata can be added via configuration (`quarkus.log.handler.splunk.include-thread-name`, etc.).

The extension also provides the support of the resolution of MDC scoped properties, as defined in https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/logging_with_jboss_eap#log_formatters[JBoss supported formatters].
MDC key/values are sent as https://docs.splunk.com/Splexicon\:Indexedfield[indexed fields] in the event.

A structured log event looks like:

[source,json]
----
{
  "time": "timestamp",
  "host": "hostname",
  "source": "mysource",
  "sourcetype": "mysourcetype",
  "index": "myindex",
  "event": {
    "message": "2021-10-07 ERROR The log message",
    "logger": "com.acme.MyClass",
    "severity": "ERROR",
    "exception": "java.lang.NullPointerException",
    "properties": {
      "mdc-key": "mdc-value"
    }
  }
}
----

=== Connectivity failures

Batched events that cannot be sent to the Splunk indexer will be logged to stdout:

* Formatted using console handler settings if the console handler is enabled
* Formatted using splunk handler settings otherwise

In any case, the root cause of the failure is always logged to stderr.

== Extension Configuration Reference

This extension follows the `log handlers` configuration domain that is defined by Quarkus, every configuration property of this extension will belong to the following configuration root : `quarkus.log.handler.splunk`

When present this extension is enabled by default, meaning the client would expect a valid connection to a Splunk indexer and would print an error message for every log created by the application.

So in local environment, the log handler can be disabled with the following property :

[source,properties]
----
quarkus.log.handler.splunk.enabled=false
----

Every configuration property of the extension is overridable at runtime.

include::includes/quarkus-log-handler-splunk.adoc[leveloffset=+1, opts=optional]
